### ISSUE TITLE
Mod doesn't appear to be working with the 12/19/2019 update.

### ISSUE THREAD

**Issue by Kuipo** [gokiburikin/gkbrkn_noita#4]
Description:
I loaded the game with only this mod enabled and am not seeing the menu in the top right, nor am I seeing any of the effects of the mod that I have used in the past.

It seems that the snowy update (https://www.youtube.com/watch?v=AbOwlheDVh8) broke something.

**Comment by gokiburikin** [comment]
This should be fixed by https://github.com/gokiburikin/gkbrkn_noita/commit/93781fe8a6e2bbf121843d67e0b3b68f783eae0d

**Comment by Kuipo** [comment]
Unfortunately I'm still not seeing it.  I've reinstalled the game and the mod by itself with no other mods and still not seeing the menu.  Any suggestions?

**Comment by gokiburikin** [comment]
Make sure you're downloading the correct latest version (https://github.com/gokiburikin/gkbrkn_noita/releases), make sure the file path is correct (noita/mods/gkbrkn_noita) and make sure the menu isn't appearing at the beginning in the top right / you're not seeing a message that it was auto-hidden. A message shows up in the bottom left if it was hidden for you.

If after all of that it's still not working then backup your save file and see if it works on a fresh save file.
